### ISSUE TITLE
Matched term is from MP within the homo sapiens section of the phenogrid

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/phenogrid#263] opened 2018-10-24 21:59 UTC
![image](https://user-images.githubusercontent.com/3658863/47464208-62aad400-d79d-11e8-8a1a-75d281208c3d.png)

**Comment by kshefchek** [comment] 2018-10-24 22:38
Dupe of #264 (I think?) @jmcmurry pls reopen if I'm mistaken.

**Closed by kshefchek** 2018-10-24 22:38 UTC

**Comment by jmcmurry** [comment] 2018-10-24 23:15
yes; a dupe; there was a glitch and I didn't realize that it posted
